server:
    port: 8080
spring:
    webflux:
        base-path: ${CONTEXT_PATH:}

    application:
        name: '@name@'

    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 10MB

    jackson:
        mapper:
            DEFAULT_VIEW_INCLUSION: true

    output:
        ansi:
            enabled: ALWAYS

    r2dbc:
        url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:test}
        username: ${DB_USER:}
        password: ${DB_PASSWORD:}
        properties:
            schema: ${market-app.default-database-schema}
        pool:
            enabled: true
            initial-size: 5
            max-size: 11
            max-idle-time: 30s
            max-life-time: 10m
            validation-query: SELECT 1  

    data:
        redis:
            database: ${REDIS_DB:0}
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}
            username: ${REDIS_USER:}
            password: ${REDIS_PASSWORD:}


    liquibase:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:test}
        user: ${DB_USER:}
        password: ${DB_PASSWORD:}
        enabled: true
        change-log: classpath:/db/changelog/db.changelog-master.yml
        default-schema: ${market-app.default-database-schema}
        parameters:
            schema: ${market-app.default-database-schema}        

    security:
        oauth2:
            client:
                provider:
                    keycloak:
                        issuer-uri: ${OAUTH_ISSUER_URI}
                        token-uri: ${OAUTH_ISSUER_URI}/protocol/openid-connect/token
                        authorization-uri: ${OAUTH_ISSUER_URI}/protocol/openid-connect/auth
                    payment-service:
                        issuer-uri: ${OAUTH_ISSUER_URI}
                        token-uri: ${OAUTH_ISSUER_URI}/protocol/openid-connect/token
                registration:
                    keycloak:
                        authorizationGrantType: authorization_code
                        provider: keycloak
                        client-id: ${OAUTH_CLIENT_ID}
                        client-secret: ${OAUTH_CLIENT_SECRET}
                        redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
                        scope: openid, profile, email
                    payment-service:
                        authorization-grant-type: client_credentials
                        provider: payment-service
                        client-id: ${OAUTH_CLIENT_ID}
                        client-secret: ${OAUTH_CLIENT_SECRET}
                        scope: openid


logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG

market-app:
    default-database-schema: ${DB_SCHEMA:public}
    cors-origins: ${CORS_ORIGINS:*}
    payment-service-host: ${PAYMENT_SERVICE_HOST:http://localhost:8080}