services:
  payment-service:
    container_name: payment-service
    restart: unless-stopped
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - 8088:8080
    expose:
      - 8080
    env_file:
      - .env
    environment:
      DB_SCHEMA: payment
    depends_on:
      - postgres
    networks:
      - market-app
    
  market-app:
    container_name: market-app
    restart: unless-stopped
    build:
      context: ./market-app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - payment-service
    env_file:
      - .env
    environment:
      DB_SCHEMA: market_app
    networks:
      - market-app

  postgres:
    container_name: postgres
    image: postgres:16.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5439:5432
    volumes:
      - postgres-market-app-data:/var/lib/postgresql/data
    networks:
      - market-app

  redis:
    image: redis:8.4.0
    container_name: redis-market-app
    restart: unless-stopped
    command: >
      sh -c '
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    expose:
      - 6379
    volumes:
      - redis-market-app:/resources
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/users.acl:/usr/local/etc/redis/users.acl
    networks:
      - market-app

volumes:
  postgres-market-app-data:
  redis-market-app:

networks:
  market-app:
    external: true